common: &common
  :original_description:
    :source_key: description
  :id:
  :name:
    :source_key: event_name
  :source:

contact_attributes: &contact_attributes
  :email:
  :first_name:
  :last_name:
  :person_title:
  :phone:
  :post:

venue_attributes: &venue_attributes
  :city:
  :country:
    :source_key: country_name
  :name:
  :postal_code:
  :state:
  :street:

DL:
  <<: *common
  :click_url:
  :url:

SHARED_ITA_USTDA: &shared_ita_ustda
  <<: *common
  :click_url:
  :cost:
  :end_date:
  :industries:
    :source_key: industry
  :registration_title:
  :registration_url:
    :source_key: registration_link
  :start_date:
  :url:

ITA:
  <<: *shared_ita_ustda
  :contacts:
    :attributes:
      <<: *contact_attributes
  :event_type:
  :venues:
    :attributes:
      <<: *venue_attributes
      :name:
        :source_key: location

SBA:
  <<: *common
  :contacts:
    :attributes:
      <<: *contact_attributes
  :cost:
  :end_date:
  :end_time:
  :event_type:
  :industries:
    :source_key: industry
  :registration_click_url:
    :source_key: click_url
  :registration_url:
    :source_key: registration_link
  :start_date:
  :start_time:
  :time_zone:
  :venues:
    :attributes:
      <<: *venue_attributes

USTDA:
  <<: *contact_attributes
  <<: *shared_ita_ustda
  :cost_currency:
  :end_time:
  :name:
    :source_key: title
  :start_time:
  :venues:
    :attributes:
      <<: *venue_attributes
      :name:
        :source_key: venue
